[[event]]
time.post = "2023-03-14T00:00:00"
time.warn = "30 minutes"
priority = "low"
message.main = "welcome!"
message.additional = "welcoming text"

[[event]]
time.post = "2024-08-27T00:00:00"
priority = "critical"
message = { main = "second new message" }
